### ISSUE TITLE
Product Dashboard Slow Response Time

### ISSUE THREAD

**Issue by jacksod1** [Hygieia/api#115]
I've encountered some product dashboard slow response times.  It takes up to 3 minutes to load the product dashboard from a single client.  This maxes out the hygieia api container CPU while it is loading the product dashboard.  I traced this issue down to PipelineServiceImpl.java.  When a project has many commits (in our case thousands) it must loop through those thousand commits for each stage and compare the commits to calculate the time it takes to move commits through to each stage.

**Affects:** \<api-version-number>.

---

**Comment by jacksod1** [comment]
https://github.com/Hygieia/api/blob/41ff8c6e4cafef2adb698afd9de46f24ee2534f9/src/main/java/com/capitalone/dashboard/service/PipelineServiceImpl.java#L234-L254

**Comment by rvema** [comment]
@jacksod1 please feel free to implement the appropriate fix for the issue. We greatly value your contribution
