### ISSUE TITLE
Anonymous user can get the user detials and able to see all the tools data which are configured in dashboards.

### ISSUE THREAD

**Issue by HaasyaDhanvika** [Hygieia/api#178]
**Affects:** latest.

---

After successfully configuring all the tools collectors in hygieia dashboard, any Anonymous user can see the user details and also able to see the all the data available in hygieia dashboards.

Is there any way to disable this type of api calls.

**Comment by rvema** [comment]
This is by design intentionally. You are welcome to create a fork and use it per your needs.
