### ISSUE TITLE
Remote dashboard creation 401 Unauthorized error

### ISSUE THREAD

**Issue by Booma-Baskaran** [Hygieia/api#18]
Hi,

I am trying to automate the dashboard creation using Hygieia API by making http://localhost:8080/api/dashboard/remoteCreate POST call. Below are the responses from swagger and Postman,

Swagger:
![image](https://user-images.githubusercontent.com/36442233/56682993-4e835900-6692-11e9-826d-d1cba80db044.png)

Postman:
I have generated the API Token using Admin menu and then did base64 encoding though I am getting 401 error,

![image](https://user-images.githubusercontent.com/36442233/56683388-09abf200-6693-11e9-9cbd-108fd41872ba.png)

Thanks,
Booma Baskaran.

**Comment by rvema** [comment]
@Booma-Baskaran Can you confirm if the above issue is still a problem?

**Comment by Booma-Baskaran** [comment]
@rvema No. I can able to make a REST call.
