### ISSUE TITLE
DockerFile will give error when doing docker run, need some guide on docker setup

### ISSUE THREAD

**Issue by YeWang555** [hygieia/api#255]
**Affects:** \<api-version-number>.

---

Our company are trying to start using hygieia for displaying metrics. We are stuck when trying to setup with docker images with API and UI. We attempted to do docker run after we build the image with dockerfile originally attached in the repo(master branch).  but it kept failing. And we tried to modify the dockerfile but still having issue with it. Would it be possible to have someone update the dockerfile in master branch or share what exactly we need modify in dockerfile in order to bring up the API component?

**Comment by abjoseph** [comment]
Hi @YeWang555, I see you closed this issue as completed, was the Dockerfile updated or did your company decide to go in another direction?
