### ISSUE TITLE
Swagger Issue

### ISSUE THREAD

**Issue by gopiprasanthpotipireddy** [Hygieia/api#58]
Swagger UI is showing controllers till 
generic-collector-item-controller after that no controllers are visible .

![image](https://user-images.githubusercontent.com/14222254/69330560-289a5300-0c79-11ea-8d90-249adca073e1.png)

**Comment by rvema** [comment]
It’s a known issue and same as #14 . Closing this issue and if you have bandwidth please contribute back for the fix
